import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { getAllPost, Post } from '../lib/data'
import { getDateStr } from './utils'

const Home: NextPage = (props: { posts: Post[] }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      </main>
      <div className="space-y-4">
        {props.posts.map((post, index) => (
          <PostItem key={post.slug} {...post} />
        )
        )}
      </div>
    </div>
  )
}

export async function getStaticProps(context: any) {
  const allPosts = getAllPost();
  console.log('allPosts', allPosts);
  return {
    props: {
      posts: allPosts ?? []
    }
  }
}

function PostItem(post: Post) {
  return (
    <div className="border border-blue-300 p-4 shadow rounded hover:shadow-md hover:border-black-800 transition duration-200 ease-in" >
      <div >
        <Link href={`/blog/${post.slug}`}>
          <a className="text-lg font-bold">{post.title}</a>
        </Link>
      </div>
      <div className="text-gray-600 text-xs">{getDateStr(post.date)}</div>
      <div>{post.content}</div>
    </div>
  )
}

export default Home